export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
      "Floating castle above the clouds",
  "Cyberpunk Tokyo street at night",
  "A dragon flying over a neon city",
  "Alien jungle with glowing plants",
  "Futuristic samurai in battle armor",
  "Magical forest with giant mushrooms",
  "Desert planet with two suns",
  "A portal to another dimension",
  "Sci-fi city with flying cars",
  "Interstellar traveler on a distant planet",
  "A melting clock in a field of flowers",
  "A human made of galaxies",
  "Infinite staircase in the clouds",
  "Floating geometric shapes in space",
  "A tree growing in the shape of a face",
  "Abstract colorful vortex",
  "Giant fish flying over a desert",
  "Cracked planet with glowing core",
  "Robot painting a sunset",
  "Surreal city underwater",
  "Cybernetic forest with neon trees",
  "Ancient ruins on a floating island",
  "Galaxy inside a glass bottle",
  "Astronaut playing guitar on the moon",
  "Spaceship crash in a jungle",
  "City of mirrors at dusk",
  "A fox made of fire",
  "Dreamlike desert with pastel skies",
  "Robot with butterfly wings",
  "Mechanical octopus in deep sea",
  "Frozen waterfall on another planet",
  "Island made of crystals",
  "Digital spirit in a forest",
  "Storm over a lava ocean",
  "Birds made of stained glass",
  "Alien carnival at night",
  "Retro-futuristic diner",
  "Cyber angel descending from the sky",
  "Post-apocalyptic landscape with ruins",
  "Floating library in the sky",
  "Robot dog in a futuristic park",
  "Samurai walking through a neon alley",
  "Sky full of planets and stars",
  "Space whale swimming through galaxies",
  "An eye in the center of a flower",
  "Garden on a spaceship",
  "Knight made of vines and leaves",
  "Digital city in a snow globe",
  "Ocean with bioluminescent waves",
  "Portal inside a cave",
  "Ship sailing in the clouds",
  "Time machine in a forest",
  "Mechanical bird in flight",
  "Space train traveling through stars",
  "Cyberpunk motorcycle race",
  "Alien temple glowing in darkness",
  "Mirror world hidden in a forest",
  "Pixelated desert landscape",
  "Castle made of books",
  "Ancient tree with glowing runes",
  "Rainbow-colored galaxy spiral",
  "Giant hand rising from the sea",
  "Sky bridge between two planets",
  "Underwater library",
  "Dragon made of stars",
  "Samurai standing in a rain of fire",
  "Colorful aurora over a cyber city",
  "Dystopian skyline at sunset",
  "Electric jellyfish in the sky",
  "Portal opening in the ocean",
  "Mechanical butterfly resting on a flower",
  "Fireflies in a crystal cave",
  "Abandoned robot in a wild garden",
  "Living skyscraper made of vines",
  "Robot meditating under a bonsai tree",
  "Dreamlike bridge over a pink river",
  "Tornado of glowing code",
  "Mechanical dragon curled on a mountain",
  "Street made of glass",
  "Galaxy inside an hourglass",
  "Floating whales in a pastel sky",
  "Neon tunnel to another world",
  "Crystals growing from an astronaut’s helmet",
  "Alien playground with abstract shapes",
  "Fantasy warrior riding a phoenix",
  "Sunken pirate ship in glowing waters",
  "Treehouse city in a floating tree",
  "Knight battling a giant robot",
  "Whale swimming through a dreamscape",
  "Storm clouds shaped like wolves",
  "Robot DJ in a glowing club",
  "Portal to a retro 80s city",
  "Fire dragon wrapped around a planet",
  "Cyber elf in glowing armor",
  "Forest with floating fire orbs",
  "Moonlight shining on a crystal lake",
  "Robot with vines growing out of it",
  "Witch flying over a futuristic city",
  "Retro robot in a meadow",
  "Time traveler in a glowing portal",
  "Ship sailing through space clouds",
  "Wizard casting a spell in space",
  "Digital cathedral with glowing arches",
  "Spaceship made of light",
  "Floating stone rings around a mountain",
  "Cyberpunk deer in a neon forest",
  "Holographic ocean shore",
  "Wolves howling at digital moon",
  "Steampunk village in the sky",
  "Mirror maze in the desert",
  "Abstract energy ball floating",
  "Monk meditating on a floating rock",
  "Cyborg lion roaring under neon light",
  "Planet with rings of water",
  "Robot gardener in a glowing greenhouse",
  "Old computer floating in space",
  "Cyber angel with neon wings",
  "Bioluminescent jungle animals",
  "Mechanical rose blooming",
  "Digital phoenix flying through fire",
  "Skyscrapers made of crystals",
  "Cyber samurai on a digital horse",
  "Virtual reality dreamscape",
  "Moon with ancient symbols",
  "Robot exploring a haunted house",
  "Witch casting digital spells",
    "Tree with glowing eyes",
  "Pixelated storm above a castle",
  "Ocean in the shape of a clock",
  "Bird flying through a portal",
  "Astronaut discovering alien art",
  "Futuristic underwater base",
  "Magic staff glowing with symbols",
  "Ancient alien ruins on Mars",
  "A dragon made of circuits",
  "Futuristic train in a rainbow tunnel",
  "Steam-powered flying ship",
  "Temple on top of a giant turtle",
  "Cybernetic desert with neon cacti",
  "Digital flowers blooming at night",
  "Robot in a flower field",
  "Pixel bridge over a lava river",
  "Glowing mountain in the clouds",
  "Giant jellyfish spaceship",
  "Neon crystal cave explorer",
  "Mechanical unicorn running",
  "Alien lake under twin moons",
  "Futuristic treehouse village",
  "AI brain in a glass container",
  "Storm made of data",
  "Digital fox running through code",
  "Spaceship shaped like a bird",
  "Giant robot head in a forest",
  "Light particles forming a dragon",
  "AI eye floating in a void",
  "Biotech hive city",
  "Time loop vortex in space",
  "Alien child drawing on moon dust",
  "Solar system orbiting a tree",
  "Colorful clouds raining stars",
  "Wormhole opening over Earth",
  "Neon-colored cyber castle",
  "AI dreamscape of shifting colors",
  "Circuit board city at night",
  "Futuristic temple above lava lake",
  "Ancient golem in a digital forest",
  "Mountain with a heart-shaped crater"

  ];