import React, { useEffect, useState } from 'react';
import {Loader,FormField,Card} from '../components';

const RenderCards = ({data, title}) => {
  if(data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  )
}


const Home = () => {

 
  const [allPosts, setallPosts] = useState([])
 
    const fetchPosts = async () => {
      
      try {
      const response = await fetch('http://localhost:3000/api/v1/posts/fetch',{
         method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          }
      });
      if (response.ok) {
        const result = await response.json();
          setallPosts(result.data.reverse())
      }
      } catch (err) {
      alert(err);
      } 
    };

  useEffect(()=>{
  
    fetchPosts();
  },[])
  return (
    <section className='max-w-7xl mx-auto'>
      <div className='grid place-items-center w-full'>
        <h1 className="font-extrabold text-[#011f35] lg:text-5xl text-3xl uppercase font-sans text-center ">The Community Showcase</h1>
        <p className="mt-5 ml-2 text-[#000000] lg:text-xl text-sm max-w-[500px] text-center">Browse through a collection imaginative and visually stunning images generated by <span className='text-[#234ffe] '>DALL- AI</span></p>
      </div>
      {/* <div className="mt-16">
        <FormField placeholder="Search posts by their prompt..." />
      </div> */}
      <div className="mt-10">
        <div
          className="boxcontai columns-1 md:columns-2 lg:columns-3 xl:columns-4 max-w-[100vw]"
          
        >
          {allPosts.map((data, index) => (
            <Card key={index} data={data} />
          ))}
        </div>
      </div>
    </section>
  )
}

export default Home
